### PR TITLE
Hackathon save the date as a separate page

### PR DESCRIPTION
**Pull request by cmaumet**
Just a few tweaks to enable the display of the hackathon save the date as its own separate page. 

@Remi-Gau: are you happy for me to remove the hackathon save-the-date form the main landing page now that we have a separate page we can point to? We can probably refer directly to the page, the URL will be: https://ossig.netlify.com/hackathon/.

We still need to find how to solve the fact that the markdown is not displayed as expected...

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Actually I think I had tried that approach but I am not sure the URL worked in the end when it was deployed by the continuous integration.

So let me merge this and see how the PR is then rendered by CI on the OHBM/ossig repo and take it from there.

**Comment by Remi-Gau** [comment]
Yeah this is what I was getting on the CI side: https://deploy-preview-3--ossig.netlify.com/hackathon/

**Comment by cmaumet** [comment]
@Remi-Gau: Thanks for deploying :D I don't manage to get the preview (the page never seems to load). Is that also what you are experiencing?

**Comment by Remi-Gau** [comment]
> @Remi-Gau: Thanks for deploying :D I don't manage to get the preview (the page never seems to load). Is that also what you are experiencing?

Yup that is the problem I was talking about. Not sure if this is specific to deploy a PR and if we won't have the problem when merging in master.

**Comment by cmaumet** [comment]
That's strange because the local behaviour looks fine... Maybe we will have to double-check in prod ?

**Comment by Remi-Gau** [comment]
> That's strange because the local behaviour looks fine... Maybe we will have to double-check in prod ?

My thought too. It is not like the website get SO MUCH traffic that we are going to break the internet if we push this in prod "just to check".

**Comment by cmaumet** [comment]
+1 but maybe let's check until we find how to solve the markdown display? 

As far as I can see the markdown elements are properly recognized as headings but the styles seem to be missing... Maybe a CSS that is not found...

**Pull request merged**
